"""Generate portable Playroom tokens and icons. Python standard library only."""
from pathlib import Path
import argparse
import copy
import json
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).parent
GENERATED = 'Generated by design-system/build.py. Edit tokens.json or icons.json instead.'


def kebab(value):
    return re.sub(r'([A-Z])', r'-\1', str(value)).lower()


def literal(value):
    return json.dumps(value, indent=2, ensure_ascii=False)


def generate():
    source = json.loads((ROOT / 'tokens.json').read_text())
    icons = json.loads((ROOT / 'icons.json').read_text())
    colors = source['color']
    for name, value in colors.items():
        if not re.fullmatch(r'#[0-9A-F]{6}', value):
            raise ValueError(f'Invalid color: {name}')
    tokens = copy.deepcopy(source)
    for group, roles in tokens['semantic'].items():
        tokens['semantic'][group] = {role: colors[color] for role, color in roles.items()}
    for shadow in tokens['shadow'].values():
        shadow['color'] = colors[shadow['color']]

    native = {}
    for role, spec in tokens['type'].items():
        native[role] = {
            'fontFamily': tokens['font'][spec['font']]['nativeAliases'][str(spec['weight'])],
            'fontSize': spec['size'], 'lineHeight': spec['lineHeight'],
            'letterSpacing': spec['letterSpacing'],
        }

    declarations = []
    def css(name, value):
        declarations.append(f'  --sl-{name}: {value};')

    for name, value in colors.items():
        css(f'color-{kebab(name)}', value)
    for group, roles in tokens['semantic'].items():
        for role, value in roles.items():
            css(f'{group}-{kebab(role)}', value)
    for name, spec in tokens['font'].items():
        css(f'font-{name}', f'"{spec["family"]}", {spec["webFallback"]}')
    for name, value in tokens['type'].items():
        prefix = f'type-{kebab(name)}'
        css(prefix+'-family', f'var(--sl-font-{value["font"]})')
        css(prefix+'-weight', value['weight'])
        for prop in ('size', 'lineHeight', 'letterSpacing'):
            css(f'{prefix}-{kebab(prop)}', f'{value[prop]}px')
    for group in ('space', 'radius', 'border', 'control', 'layout'):
        for name, value in tokens[group].items():
            css(f'{group}-{kebab(name)}', f'{value}px')
    for name, value in tokens['motion']['duration'].items():
        css(f'duration-{name}', f'{value}ms')
    for name, value in tokens['motion']['easing'].items():
        css(f'ease-{name}', 'cubic-bezier('+', '.join(map(str, value))+')')
    css('pressed-offset-y', f'{tokens["motion"]["pressedOffsetY"]}px')
    css('duration-reduced', f'{tokens["motion"]["reducedDuration"]}ms')
    for name, spec in tokens['shadow'].items():
        css('shadow-'+name, ' '.join(f'{spec[key]}px' for key in ('x','y','blur','spread'))+' '+spec['color'])
    reduced = '\n'.join(f'    --sl-duration-{name}: 0ms;' for name in tokens['motion']['duration'])

    outputs = {
        'tokens.resolved.json': literal(tokens)+'\n',
        'tokens.ts': f'// {GENERATED}\nexport const tokens = {literal(tokens)} as const;\n\nexport type SignloopTokens = typeof tokens;\n',
        'native.ts': f'// {GENERATED}\n// Load each font variant under its documented alias before rendering.\nexport {{ tokens }} from "./tokens";\n\nexport const textStyles = {literal(native)} as const;\n\nexport type TextRole = keyof typeof textStyles;\n',
        'tokens.css': f'/* {GENERATED} */\n:root {{\n'+ '\n'.join(declarations)+'\n}\n\n@media (prefers-reduced-motion: reduce) {\n  :root {\n'+reduced+'\n  }\n}\n',
        'icons.ts': f'// {GENERATED}\n// $surface means the background beneath the icon; currentColor means foreground.\nexport const iconViewBox = {literal(icons["viewBox"])};\nexport const iconStrokeWidth = {tokens["control"]["iconStrokeWidth"]};\nexport const icons = {literal(icons["icons"])} as const;\nexport type IconName = keyof typeof icons;\n',
    }
    for name, shapes in icons['icons'].items():
        root = ET.Element('svg', {
            'xmlns': 'http://www.w3.org/2000/svg', 'viewBox': icons['viewBox'],
            'width': '24', 'height': '24', 'fill': 'none', 'stroke': 'currentColor',
            'stroke-width': str(tokens['control']['iconStrokeWidth']),
            'stroke-linecap': 'round', 'stroke-linejoin': 'round',
        })
        for shape in shapes:
            if shape['tag'] not in ('path', 'circle'):
                raise ValueError(f'Unsupported shape in {name}')
            attrs = {kebab(key): str(value) for key, value in shape.items() if key != 'tag'}
            # Standalone SVG defaults to the raised surface. Native adapters can
            # substitute the actual component surface using the shape registry.
            if attrs.get('fill') == '$surface':
                attrs['fill'] = colors['paper']
            ET.SubElement(root, shape['tag'], attrs)
        outputs[f'assets/icons/{name}.svg'] = ET.tostring(root, encoding='unicode')+'\n'
    return outputs, tokens


def luminance(color):
    channels = [int(color[i:i+2],16)/255 for i in (1,3,5)]
    values = [c/12.92 if c <= .04045 else ((c+.055)/1.055)**2.4 for c in channels]
    return sum(c*w for c,w in zip(values,(.2126,.7152,.0722)))


def check_contrast(tokens):
    roles = tokens['semantic']
    pairs = [('default','canvas'),('default','raised'),('secondary','canvas'),
             ('secondary','raised'),('onPrimary','primary'),('onSecondary','secondary'),
             ('success','success'),('caution','caution'),('destructive','raised'),
             ('onInverse','inverse'),('onInverseSecondary','inverse')]
    for text, surface in pairs:
        a,b=sorted([luminance(roles['text'][text]),luminance(roles['surface'][surface])])
        ratio=(b+.05)/(a+.05)
        if ratio < 4.5:
            raise ValueError(f'Text contrast below 4.5:1: {text}/{surface} ({ratio:.2f}:1)')
    return len(pairs)


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Verify generated files without writing')
    args=parser.parse_args()
    outputs,tokens=generate()
    contrast_pairs = check_contrast(tokens)
    mismatches=[]
    for name, content in outputs.items():
        path=ROOT/name
        if args.check:
            if not path.exists() or path.read_text()!=content:
                mismatches.append(name)
        else:
            path.parent.mkdir(parents=True,exist_ok=True)
            path.write_text(content)
    if mismatches:
        raise SystemExit('Regenerate stale or missing files: '+', '.join(mismatches))
    print(f'{"Verified" if args.check else "Generated"} {len(outputs)} files; {contrast_pairs} text/surface contrast pairs pass 4.5:1.')


if __name__ == '__main__':
    main()
