// Generated by design-system/build.py. Edit tokens.json or icons.json instead.
// $surface means the background beneath the icon; currentColor means foreground.
export const iconViewBox = "0 0 24 24";
export const iconStrokeWidth = 1.75;
export const icons = {
  "back": [
    {
      "tag": "path",
      "d": "m14 6-6 6 6 6"
    }
  ],
  "arrow": [
    {
      "tag": "path",
      "d": "M5 12h14m-6-6 6 6-6 6"
    }
  ],
  "pause": [
    {
      "tag": "path",
      "d": "M9 5v14M15 5v14",
      "strokeWidth": 3
    }
  ],
  "play": [
    {
      "tag": "path",
      "d": "m9 5 10 7-10 7Z",
      "fill": "currentColor",
      "stroke": "none"
    }
  ],
  "close": [
    {
      "tag": "path",
      "d": "m6 6 12 12M18 6 6 18"
    }
  ],
  "more": [
    {
      "tag": "circle",
      "cx": 5,
      "cy": 12,
      "r": 1
    },
    {
      "tag": "circle",
      "cx": 12,
      "cy": 12,
      "r": 1
    },
    {
      "tag": "circle",
      "cx": 19,
      "cy": 12,
      "r": 1
    }
  ],
  "check": [
    {
      "tag": "path",
      "d": "m5 12 4 4L19 6"
    }
  ],
  "camera": [
    {
      "tag": "path",
      "d": "M4 7h4l2-3h4l2 3h4v13H4Z"
    },
    {
      "tag": "circle",
      "cx": 12,
      "cy": 13,
      "r": 4
    }
  ],
  "frame": [
    {
      "tag": "path",
      "d": "M8 4H4v4m12-4h4v4M4 16v4h4m8 0h4v-4"
    },
    {
      "tag": "path",
      "d": "M9 11a3 3 0 1 1 6 0m-9 7q6-9 12 0"
    }
  ],
  "sun": [
    {
      "tag": "circle",
      "cx": 12,
      "cy": 12,
      "r": 4
    },
    {
      "tag": "path",
      "d": "M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2"
    }
  ],
  "volume": [
    {
      "tag": "path",
      "d": "M4 9h4l5-4v14l-5-4H4Z M17 8q5 4 0 8"
    }
  ],
  "muted": [
    {
      "tag": "path",
      "d": "M4 9h4l5-4v14l-5-4H4Z m13 0 5 6m0-6-5 6"
    }
  ],
  "edit": [
    {
      "tag": "path",
      "d": "m5 15 10-10 4 4-10 10-5 1Z m8-8 4 4"
    }
  ],
  "repeat": [
    {
      "tag": "path",
      "d": "M5 8a8 8 0 1 1-1 8M5 3v6h6"
    }
  ],
  "transcript": [
    {
      "tag": "path",
      "d": "M5 3h14v18H5Z m4 5h6m-6 4h6m-6 4h4"
    }
  ],
  "settings": [
    {
      "tag": "path",
      "d": "M4 7h16M4 17h16"
    },
    {
      "tag": "circle",
      "cx": 9,
      "cy": 7,
      "r": 3,
      "fill": "$surface"
    },
    {
      "tag": "circle",
      "cx": 15,
      "cy": 17,
      "r": 3,
      "fill": "$surface"
    }
  ],
  "exit": [
    {
      "tag": "path",
      "d": "M11 4H4v16h7m2-13 5 5-5 5M8 12h12"
    }
  ],
  "info": [
    {
      "tag": "circle",
      "cx": 12,
      "cy": 12,
      "r": 9
    },
    {
      "tag": "path",
      "d": "M12 11v6m0-10v.2"
    }
  ],
  "offline": [
    {
      "tag": "path",
      "d": "M3 8q9-9 18 0M6 12q6-6 12 0m-9 4q3-3 6 0M3 3l18 18"
    }
  ],
  "loading": [
    {
      "tag": "path",
      "d": "M20 12a8 8 0 1 1-8-8m0 0v4m0-4h4"
    }
  ],
  "hand": [
    {
      "tag": "path",
      "d": "M8 12V7a2 2 0 0 1 4 0V5a2 2 0 0 1 4 0v3a2 2 0 0 1 4 0v7c0 5-3 7-7 7-3 0-5-2-7-5l-3-4c-1-2 1-4 3-2l2 2Z"
    }
  ]
} as const;
export type IconName = keyof typeof icons;
