// Generated by design-system/build.py. Edit tokens.json or icons.json instead.
// Load each font variant under its documented alias before rendering.
export { tokens } from "./tokens";

export const textStyles = {
  "hero": {
    "fontFamily": "SignloopDisplayMedium",
    "fontSize": 48,
    "lineHeight": 52,
    "letterSpacing": -1
  },
  "title": {
    "fontFamily": "SignloopDisplayMedium",
    "fontSize": 40,
    "lineHeight": 44,
    "letterSpacing": -0.8
  },
  "sheetTitle": {
    "fontFamily": "SignloopDisplayMedium",
    "fontSize": 28,
    "lineHeight": 32,
    "letterSpacing": -0.5
  },
  "sectionTitle": {
    "fontFamily": "SignloopDisplayMedium",
    "fontSize": 24,
    "lineHeight": 28,
    "letterSpacing": -0.3
  },
  "status": {
    "fontFamily": "SignloopDisplayMedium",
    "fontSize": 20,
    "lineHeight": 24,
    "letterSpacing": 0
  },
  "caption": {
    "fontFamily": "SignloopDisplayRegular",
    "fontSize": 24,
    "lineHeight": 28,
    "letterSpacing": -0.2
  },
  "captionLarge": {
    "fontFamily": "SignloopDisplayRegular",
    "fontSize": 30,
    "lineHeight": 36,
    "letterSpacing": -0.2
  },
  "body": {
    "fontFamily": "SignloopBodyRegular",
    "fontSize": 16,
    "lineHeight": 24,
    "letterSpacing": 0
  },
  "button": {
    "fontFamily": "SignloopBodySemibold",
    "fontSize": 16,
    "lineHeight": 24,
    "letterSpacing": 0
  },
  "label": {
    "fontFamily": "SignloopBodySemibold",
    "fontSize": 14,
    "lineHeight": 20,
    "letterSpacing": 0
  },
  "supporting": {
    "fontFamily": "SignloopBodyRegular",
    "fontSize": 14,
    "lineHeight": 20,
    "letterSpacing": 0
  }
} as const;

export type TextRole = keyof typeof textStyles;
