// Generated by design-system/build.py. Edit tokens.json or icons.json instead.
export const tokens = {
  "name": "Honk & Tell Playroom",
  "version": "0.1.0",
  "units": "Logical pixels / points; milliseconds for duration",
  "color": {
    "ink": "#49312D",
    "inkStrong": "#432D2B",
    "butter": "#FFF2BA",
    "paper": "#FFFCF0",
    "coral": "#F87960",
    "blue": "#A7C6E8",
    "muted": "#75675F",
    "onInkMuted": "#D9C9B9",
    "line": "#D6CEBE",
    "captionShadow": "#DCC480",
    "successSurface": "#E3F0D2",
    "successInk": "#40532B",
    "cautionSurface": "#FFEDC3",
    "cautionInk": "#70502B",
    "dangerInk": "#AA3E29",
    "focus": "#315991"
  },
  "semantic": {
    "surface": {
      "canvas": "#FFF2BA",
      "raised": "#FFFCF0",
      "primary": "#F87960",
      "secondary": "#A7C6E8",
      "inverse": "#49312D",
      "success": "#E3F0D2",
      "caution": "#FFEDC3"
    },
    "text": {
      "default": "#49312D",
      "secondary": "#75675F",
      "onPrimary": "#432D2B",
      "onSecondary": "#49312D",
      "onInverse": "#FFFCF0",
      "onInverseSecondary": "#D9C9B9",
      "success": "#40532B",
      "caution": "#70502B",
      "destructive": "#AA3E29"
    },
    "stroke": {
      "strong": "#49312D",
      "subtle": "#D6CEBE",
      "focus": "#315991"
    }
  },
  "font": {
    "display": {
      "family": "Fredoka",
      "webFallback": "'Arial Rounded MT Bold', sans-serif",
      "nativeAliases": {
        "400": "SignloopDisplayRegular",
        "500": "SignloopDisplayMedium"
      }
    },
    "body": {
      "family": "DM Sans",
      "webFallback": "Arial, sans-serif",
      "nativeAliases": {
        "400": "SignloopBodyRegular",
        "500": "SignloopBodyMedium",
        "600": "SignloopBodySemibold"
      }
    }
  },
  "type": {
    "poster": {
      "font": "display",
      "weight": 500,
      "size": 96,
      "lineHeight": 80,
      "letterSpacing": -3.5
    },
    "featuredCaption": {
      "font": "display",
      "weight": 400,
      "size": 32,
      "lineHeight": 34,
      "letterSpacing": -0.5
    },
    "hero": {
      "font": "display",
      "weight": 500,
      "size": 48,
      "lineHeight": 48,
      "letterSpacing": -1
    },
    "title": {
      "font": "display",
      "weight": 500,
      "size": 40,
      "lineHeight": 42,
      "letterSpacing": -0.8
    },
    "sheetTitle": {
      "font": "display",
      "weight": 500,
      "size": 28,
      "lineHeight": 30,
      "letterSpacing": -0.5
    },
    "sectionTitle": {
      "font": "display",
      "weight": 500,
      "size": 24,
      "lineHeight": 28,
      "letterSpacing": -0.3
    },
    "status": {
      "font": "display",
      "weight": 500,
      "size": 20,
      "lineHeight": 24,
      "letterSpacing": 0
    },
    "caption": {
      "font": "display",
      "weight": 400,
      "size": 24,
      "lineHeight": 26,
      "letterSpacing": -0.2
    },
    "captionLarge": {
      "font": "display",
      "weight": 400,
      "size": 30,
      "lineHeight": 32,
      "letterSpacing": -0.2
    },
    "body": {
      "font": "body",
      "weight": 400,
      "size": 16,
      "lineHeight": 22,
      "letterSpacing": 0
    },
    "button": {
      "font": "body",
      "weight": 600,
      "size": 16,
      "lineHeight": 24,
      "letterSpacing": 0
    },
    "label": {
      "font": "body",
      "weight": 600,
      "size": 14,
      "lineHeight": 20,
      "letterSpacing": 0
    },
    "supporting": {
      "font": "body",
      "weight": 400,
      "size": 14,
      "lineHeight": 20,
      "letterSpacing": 0
    }
  },
  "space": {
    "0": 0,
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "5": 20,
    "6": 24,
    "8": 32,
    "10": 40,
    "12": 48,
    "16": 64
  },
  "radius": {
    "small": 8,
    "control": 16,
    "bubble": 20,
    "bubbleTail": 4,
    "panel": 28,
    "pill": 999
  },
  "border": {
    "hairline": 1,
    "default": 1.5,
    "emphasis": 2,
    "focus": 3
  },
  "control": {
    "minTouchTarget": 44,
    "primaryMinHeight": 52,
    "iconSize": 22,
    "compactIconSize": 20,
    "iconStrokeWidth": 1.75
  },
  "layout": {
    "screenGutter": 24,
    "compactGutter": 16,
    "componentGap": 12,
    "sectionGap": 24
  },
  "motion": {
    "duration": {
      "instant": 0,
      "press": 85,
      "feedback": 160,
      "transition": 240,
      "navigation": 280,
      "scene": 440
    },
    "easing": {
      "standard": [
        0.2,
        0,
        0,
        1
      ],
      "enter": [
        0.16,
        1,
        0.3,
        1
      ]
    },
    "pressedOffsetY": 2,
    "pressedScale": 0.975,
    "spring": {
      "touch": {
        "damping": 18,
        "stiffness": 360,
        "mass": 0.55
      },
      "sheet": {
        "damping": 42,
        "stiffness": 380,
        "mass": 0.9
      }
    },
    "reducedDuration": 0
  },
  "shadow": {
    "action": {
      "x": 0,
      "y": 3,
      "blur": 0,
      "spread": 0,
      "color": "#49312D"
    },
    "caption": {
      "x": 3,
      "y": 3,
      "blur": 0,
      "spread": 0,
      "color": "#DCC480"
    }
  }
} as const;

export type SignloopTokens = typeof tokens;
